In [1]:
import numpy as np
import pandas as pd
import math as mt
import sys
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import MinMaxScaler

eps = np.finfo(float).eps

In [2]:
dataSet = pd.read_csv("./../input_data/data 2.csv")
Class = "xAttack"
columns = list(dataSet.columns)
X = dataSet[columns[:-1]]



In [3]:
X.head(10)

duration  service  src_bytes  dst_bytes  hot  num_failed_logins  \
0         0       25        193        441    0                  0   
1         0       38          0          0    0                  0   
2         0       25        167       9724    0                  0   
3         0       20       1339          0    0                  0   
4         0       37          0          0    0                  0   
5         0       25        326       2659    0                  0   
6         0       50        105        145    0                  0   
7         0       40          0          0    0                  0   
8         0       20          0        133    0                  0   
9         0       25        226       3630    0                  0   

   num_compromised  num_root  num_file_creations  num_access_files  \
0                0         0                   0                 0   
1                0         0                   0                 0   
2                0         0                   0                 0   
3                0         0                   0                 0   
4                0         0                   0                 0   
5                0         0                   0                 0   
6                0         0                   0                 0   
7                0         0                   0                 0   
8                0         0                   0                 0   
9                0         0                   0                 0   

             ...             dst_host_count  dst_host_srv_count  \
0            ...                         15                 255   
1            ...                        255                   1   
2            ...                         39                 255   
3            ...                        134                  31   
4            ...                        255                  25   
5            ...                        255                 255   
6            ...                         21                  13   
7            ...                        255                  16   
8            ...                          2                   2   
9            ...                          7                 255   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                    1.00                    0.00   
1                    0.00                    0.07   
2                    1.00                    0.00   
3                    0.23                    0.04   
4                    0.10                    0.05   
5                    1.00                    0.00   
6                    0.62                    0.14   
7                    0.06                    0.07   
8                    0.50                    1.00   
9                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.07                         0.04   
1                         0.00                         0.00   
2                         0.03                         0.06   
3                         0.23                         0.00   
4                         0.00                         0.00   
5                         0.00                         0.00   
6                         0.10                         0.00   
7                         0.00                         0.00   
8                         0.50                         1.00   
9                         0.14                         0.01   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.04                   0.0   
1                  0.00                      0.00                   1.0   
2                  0.00                      0.00                   0.0   
3                  0.02                      0.00                   0.0   
4                  1.00                      1.00                   0.

In [4]:
Y = dataSet[[Class]]

In [5]:
Y.head(10)


xAttack
0  normal
1     dos
2  normal
3  normal
4     dos
5  normal
6  normal
7     dos
8   probe
9  normal

In [6]:
x_std = StandardScaler().fit_transform(X)

/Users/martian/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/martian/anaconda3/lib/python3.7/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [7]:
x_std

array([[-0.11453823, -0.42593636, -0.01001262, ..., -0.53533169,
        -0.38607684, -0.37498211],
       [-0.11453823,  0.362291  , -0.01009237, ..., -0.62514571,
         2.87824009,  2.77113829],
       [-0.11453823, -0.42593636, -0.01002337, ..., -0.62514571,
        -0.38607684, -0.37498211],
       ...,
       [ 0.8942439 ,  1.7568471 , -0.00917297, ..., -0.62514571,
        -0.38607684, -0.37498211],
       [-0.11453823, -1.0322651 , -0.01008907, ..., -0.62514571,
        -0.38607684, -0.37498211],
       [-0.11453823,  1.08988549, -0.01009237, ...,  1.62020478,
        -0.38607684, -0.37498211]])

In [8]:
features = x_std.T 
covariance_matrix = np.cov(features)
covariance_matrix

array([[ 1.00004000e+00,  1.02715831e-01,  8.43742819e-02,
         1.43497309e-02,  4.34568113e-03,  1.09916074e-02,
         9.46382509e-02,  9.34955382e-02,  8.77209478e-02,
         6.97225174e-02, -8.23011124e-02, -4.10379283e-02,
        -7.28263906e-02, -7.21970012e-02,  2.11972299e-01,
         2.10742568e-01,  7.63665160e-02, -1.30006546e-02,
        -4.16183202e-02,  5.62988686e-02, -1.13739480e-01,
        -1.20704675e-01,  2.65200619e-01,  2.43037619e-01,
        -2.59347890e-02, -6.68859761e-02, -6.66093944e-02,
         1.89984780e-01,  2.10908797e-01],
       [ 1.02715831e-01,  1.00004000e+00,  8.09466117e-03,
        -1.42498172e-02, -5.68042953e-02,  2.87954144e-02,
         3.69845482e-02,  3.46393940e-02,  4.10796449e-02,
         3.19389000e-02,  8.83752736e-02, -2.66181205e-01,
         2.73404074e-01,  2.70721017e-01,  1.47775257e-01,
         1.46235431e-01, -3.61681395e-01,  2.04626180e-01,
        -9.55606878e-02,  1.84243436e-01, -4.04510033e-01,
        -4.48

In [9]:
eig_vals, eig_vecs = np.linalg.eig(covariance_matrix)


In [10]:
eig_vecs

array([[-3.72814335e-03, -1.33277196e-01, -9.82099153e-02,
        -1.17781733e-01,  1.09093601e-01,  3.75448937e-01,
        -4.40073530e-01, -3.20769610e-01, -1.87217993e-01,
         3.13731481e-01,  4.75761342e-02,  7.47050967e-03,
        -3.36825224e-02, -3.86288805e-01,  3.69204675e-01,
         8.08047343e-02, -7.04681488e-02,  1.53700783e-01,
        -2.02031907e-01,  9.48309921e-02,  3.36668966e-02,
         3.19576068e-03,  2.48822087e-02, -8.22467908e-03,
         3.94103691e-03, -6.47098960e-03,  1.15081775e-03,
        -1.44680420e-03, -1.12345173e-03],
       [ 1.65678882e-01, -9.21664927e-02, -5.24127681e-02,
        -1.71833188e-01, -2.15742946e-01,  2.47542356e-01,
         1.18191297e-01, -1.04543494e-01,  7.36857259e-02,
         6.81346337e-02,  6.93160819e-02, -1.73043094e-01,
         6.13463273e-01,  4.84860195e-01,  2.86562539e-01,
         1.02067189e-01, -5.96043652e-02,  1.49518578e-01,
         1.53688624e-01,  7.80853353e-03, -1.17557802e-02,
        -2.30

In [11]:
eig_vals

array([6.73792010e+00, 4.86394323e+00, 2.61304344e+00, 1.88825019e+00,
       1.47239103e+00, 1.34445489e+00, 1.13686784e+00, 1.05599217e+00,
       9.19031673e-01, 9.62884727e-01, 9.97747022e-01, 1.00605989e+00,
       7.16997425e-01, 6.55723024e-01, 4.96856883e-01, 4.47530656e-01,
       4.12119820e-01, 4.02113812e-01, 3.45219725e-01, 2.10204295e-01,
       9.70901692e-02, 6.64827642e-02, 5.21876041e-02, 3.96458945e-02,
       2.89025639e-02, 1.63697530e-02, 1.00407728e-03, 9.49076867e-03,
       4.63468452e-03])

In [12]:
eig_dic = {}
for i in range(0,len(eig_vals)):
    eig_dic[eig_vals[i]] = eig_vecs[:,i]
cum_sum = 0
select_eig_vecs = []
attr_name = []
c = 1
total = sum(eig_vals)
for key in reversed(sorted(eig_dic.keys())):
    cum_sum += abs(key)
    correct_res = cum_sum/total
    select_eig_vecs.append(eig_dic[key])
    attr_name.append("Col-"+ str(c))
    c += 1
    if correct_res > 0.90:
        break
print(c) 
correct_res

15


0.9093190252147999

In [13]:
projected_X = x_std.dot(np.array(select_eig_vecs).T)
projected_X

array([[-2.50946520e+00,  9.52118043e-01,  8.05755168e-02, ...,
         8.50312294e-02, -4.78761528e-01,  3.80057517e-01],
       [ 1.19325993e+00, -5.59820431e+00,  2.70795585e-01, ...,
         6.43676015e-02,  4.30117879e-01,  2.64015116e-01],
       [-2.44710014e+00,  9.08939709e-01,  6.03192180e-02, ...,
         5.04823140e-02, -7.54360905e-01,  4.29615250e-01],
       ...,
       [-2.14676535e-01, -3.09877590e-01, -1.37272986e+01, ...,
         1.72825356e+01, -1.61696242e+00,  1.79863104e+00],
       [-3.46663135e+00,  5.46446031e-01, -7.44319096e-02, ...,
         3.55261207e-01,  4.57109427e-01, -7.13572892e-01],
       [ 4.01832089e+00,  1.12480793e+00, -6.01524597e-02, ...,
        -3.89962407e-03,  2.80523132e-01,  2.18831703e-01]])

In [14]:
result = pd.DataFrame(projected_X, columns = attr_name)
result[Class] = Y

In [15]:
result.to_csv("./../output_data/q-1-1_output.csv",index = False)


In [16]:
result

Col-1     Col-2      Col-3     Col-4     Col-5     Col-6     Col-7  \
0     -2.509465  0.952118   0.080576  0.089474 -0.465568 -0.264136  0.073176   
1      1.193260 -5.598204   0.270796  1.130964 -0.813104 -1.629214 -0.541853   
2     -2.447100  0.908940   0.060319  0.031070 -0.822739 -0.170783  0.098461   
3     -1.111758  0.343094  -0.004162 -0.266452 -0.166214  0.596465  0.015911   
4      3.983967  1.268863   0.050828  0.252378  0.537147 -0.561608 -0.278506   
5     -1.918467  0.882151   0.121446  1.045580 -0.724822  0.258840  0.127252   
6     -1.230931  0.184821  -0.109211 -0.877238 -0.733214  0.898992  0.394244   
7      4.050267  1.201003   0.013302 -0.047662  0.217457 -0.412005 -0.198850   
8     -1.999028 -6.546796  -0.000557 -5.260549  2.740629 -2.698112 -0.131257   
9     -2.607263  0.929966   0.062277 -0.189759 -0.628918 -0.226842  0.130734   
10    -2.051997  0.880315   0.086946  0.756532 -0.951397  0.250100  0.102138   
11    -2.180376  0.908136   0.073507  0.512361 -0.914082  0.094468  0.084202   
12    -1.447244  0.366907   0.003676 -0.517966  0.285703  0.377166 -0.011451   
13     3.568706  1.428773   0.107855  0.222540  0.548662 -0.844837 -0.446725   
14    -0.593032 -0.746345   0.076726  0.512298 -0.347186  0.297089 -0.220574   
15    -1.878860  0.864038   0.107269  1.056905 -0.955814  0.393321  0.117276   
16    -0.082046 -0.762616  -0.032968 -0.568089 -0.675698  2.217433  3.420749   
17    -2.528367  0.903175   0.057920 -0.098901 -0.726682 -0.173979  0.094510   
18     0.551193 -2.340249   0.060259 -0.240020  0.695242  1.967186  1.355163   
19    -2.206239  0.913471   0.101582  0.580307 -0.658981 -0.008507  0.119816   
20    -2.054841  0.953869   0.163824  1.187313 -0.535521  0.078882  0.030006   
21    -1.860157  0.811922   0.120103  1.161235 -0.823681  0.348831  0.091569   
22     3.413516  1.408988   0.041811 -0.109566  0.114811 -0.492355 -0.336938   
23    -2.373734  0.928202   0.085061  0.299885 -0.679618 -0.155425  0.110303   
24    -2.081787  0.884947   0.097297  0.740564 -0.894653  0.197762  0.116991   
25     3.840967  1.186162  -0.061547 -0.479211 -0.302610 -0.009895 -0.079147   
26    -1.867462  0.865158   0.117151  1.123539 -0.861451  0.375363  0.114268   
27     3.520029  1.381802   0.009480 -0.158307 -0.007763 -0.377582 -0.304635   
28    -0.102717 -7.324556  -0.574294 -1.817905  1.480058  3.191684 -3.077677   
29    -0.558977  0.342786   0.016020  0.350189 -0.491339  0.716227  0.005024   
...         ...       ...        ...       ...       ...       ...       ...   
24968  0.716463 -0.985583  -0.066255 -0.343205 -0.538117  2.776966  3.394132   
24969  3.853306  1.191567  -0.072722 -0.565416 -0.392238 -0.009518 -0.133212   
24970  2.519848  1.091738  -0.183605 -2.348310 -0.359391 -0.552605  0.027054   
24971 -2.128646  0.091694  -0.035835 -1.577894  1.093342  0.852218  0.245959   
24972 -2.232798  0.902068   0.086851  0.503259 -0.856401  0.046205  0.110522   
24973 -2.614208  0.833174   0.042041 -0.577110 -0.288505 -0.170818  0.097043   
24974  3.840264  1.192032  -0.065129 -0.489010 -0.294436 -0.004346 -0.103620   
24975 -1.154524  0.415513   0.035938  0.190044 -0.028534  0.740325 -0.024841   
24976 -1.762215  0.589218  -0.064231 -1.261399 -0.832511 -0.067475  0.573540   
24977 -2.564939 -0.553706   0.115742 -0.436992 -0.440665 -1.314125 -0.234394   
24978 -1.980658  0.892775   0.109112  0.848877 -0.801388  0.194016  0.153475   
24979 -2.313397  0.693533   0.132944  0.343481  1.231225  0.609900 -0.164715   
24980 -0.297602  0.144685  -0.073432  0.086240 -0.682291  1.181819  0.202506   
24981 -1.902125  0.865937   0.113258  1.040014 -0.852894  0.330247  0.113465   
24982 -2.340626  0.910085   0.070090  0.290490 -0.824636 -0.070063  0.089027   
24983 -2.272207  0.908964   0.087012  0.473791 -0.804743  0.000302  0.103228   
24984  3.887065  1.185551  -0.054435 -0.421695 -0.238433 -0.058221 -0.105076   
24985 -1.899047  0.883555   0.132219  1.155280 -0.591771  0.247506  0.111316   
24986  0.8

In [17]:
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=14)
Y_sklearn = sklearn_pca.fit_transform(x_std)


In [18]:
result = pd.DataFrame(Y_sklearn, columns = attr_name)
result[Class] = Y

In [19]:
result

Col-1     Col-2      Col-3     Col-4     Col-5     Col-6     Col-7  \
0     -2.509465 -0.952118  -0.080576  0.089474 -0.465568 -0.264136 -0.073176   
1      1.193260  5.598204  -0.270796  1.130964 -0.813104 -1.629214  0.541853   
2     -2.447100 -0.908940  -0.060319  0.031070 -0.822739 -0.170783 -0.098461   
3     -1.111758 -0.343094   0.004162 -0.266452 -0.166214  0.596465 -0.015911   
4      3.983967 -1.268863  -0.050828  0.252378  0.537147 -0.561608  0.278506   
5     -1.918467 -0.882151  -0.121446  1.045580 -0.724822  0.258840 -0.127252   
6     -1.230931 -0.184821   0.109211 -0.877238 -0.733214  0.898992 -0.394244   
7      4.050267 -1.201003  -0.013302 -0.047662  0.217457 -0.412005  0.198850   
8     -1.999028  6.546796   0.000557 -5.260549  2.740629 -2.698112  0.131257   
9     -2.607263 -0.929966  -0.062277 -0.189759 -0.628918 -0.226842 -0.130734   
10    -2.051997 -0.880315  -0.086946  0.756532 -0.951397  0.250100 -0.102138   
11    -2.180376 -0.908136  -0.073507  0.512361 -0.914082  0.094468 -0.084202   
12    -1.447244 -0.366907  -0.003676 -0.517966  0.285703  0.377166  0.011451   
13     3.568706 -1.428773  -0.107855  0.222540  0.548662 -0.844837  0.446725   
14    -0.593032  0.746345  -0.076726  0.512298 -0.347186  0.297089  0.220574   
15    -1.878860 -0.864038  -0.107269  1.056905 -0.955814  0.393321 -0.117276   
16    -0.082046  0.762616   0.032968 -0.568089 -0.675698  2.217433 -3.420749   
17    -2.528367 -0.903175  -0.057920 -0.098901 -0.726682 -0.173979 -0.094510   
18     0.551193  2.340249  -0.060259 -0.240020  0.695242  1.967186 -1.355163   
19    -2.206239 -0.913471  -0.101582  0.580307 -0.658981 -0.008507 -0.119816   
20    -2.054841 -0.953869  -0.163824  1.187313 -0.535521  0.078882 -0.030006   
21    -1.860157 -0.811922  -0.120103  1.161235 -0.823681  0.348831 -0.091569   
22     3.413516 -1.408988  -0.041811 -0.109566  0.114811 -0.492355  0.336938   
23    -2.373734 -0.928202  -0.085061  0.299885 -0.679618 -0.155425 -0.110303   
24    -2.081787 -0.884947  -0.097297  0.740564 -0.894653  0.197762 -0.116991   
25     3.840967 -1.186162   0.061547 -0.479211 -0.302610 -0.009895  0.079147   
26    -1.867462 -0.865158  -0.117151  1.123539 -0.861451  0.375363 -0.114268   
27     3.520029 -1.381802  -0.009480 -0.158307 -0.007763 -0.377582  0.304635   
28    -0.102717  7.324556   0.574294 -1.817905  1.480058  3.191684  3.077677   
29    -0.558977 -0.342786  -0.016020  0.350189 -0.491339  0.716227 -0.005024   
...         ...       ...        ...       ...       ...       ...       ...   
24968  0.716463  0.985583   0.066255 -0.343205 -0.538117  2.776966 -3.394132   
24969  3.853306 -1.191567   0.072722 -0.565416 -0.392238 -0.009518  0.133212   
24970  2.519848 -1.091738   0.183605 -2.348310 -0.359391 -0.552605 -0.027053   
24971 -2.128646 -0.091694   0.035835 -1.577894  1.093342  0.852218 -0.245959   
24972 -2.232798 -0.902068  -0.086851  0.503259 -0.856401  0.046205 -0.110522   
24973 -2.614208 -0.833174  -0.042041 -0.577110 -0.288505 -0.170818 -0.097043   
24974  3.840264 -1.192032   0.065129 -0.489010 -0.294436 -0.004346  0.103620   
24975 -1.154524 -0.415513  -0.035938  0.190044 -0.028534  0.740325  0.024841   
24976 -1.762215 -0.589218   0.064231 -1.261399 -0.832511 -0.067475 -0.573540   
24977 -2.564939  0.553706  -0.115742 -0.436992 -0.440665 -1.314125  0.234394   
24978 -1.980658 -0.892775  -0.109112  0.848877 -0.801388  0.194016 -0.153475   
24979 -2.313397 -0.693533  -0.132944  0.343481  1.231225  0.609900  0.164715   
24980 -0.297602 -0.144685   0.073432  0.086240 -0.682291  1.181819 -0.202506   
24981 -1.902125 -0.865937  -0.113258  1.040014 -0.852894  0.330247 -0.113465   
24982 -2.340626 -0.910085  -0.070090  0.290490 -0.824636 -0.070063 -0.089027   
24983 -2.272207 -0.908964  -0.087012  0.473791 -0.804743  0.000302 -0.103228   
24984  3.887065 -1.185551   0.054435 -0.421695 -0.238433 -0.058221  0.105076   
24985 -1.899047 -0.883555  -0.132219  1.155280 -0.591771  0.247506 -0.111316   
24986  0.8